### ISSUE TITLE
please upload the pretrained model

### ISSUE THREAD

**Issue by jianjia93** [guochengqian/TENet#1]
Hi, I just read about your paper and and loop up your project. You offer the instruction to test the result with your pretrained model, but I didn't find it in the project. Can you please upload the pretrained model? Thanks a lot!

**Comment by guochengqian** [comment]
@jianjia93 Hi, pre-trained models will be released in three days.

**Comment by guochengqian** [comment]
Pre-trained models have been released. Refer to Readme for more information. Plz.
