### ISSUE TITLE
Question about PixelShift200 data preparation

### ISSUE THREAD

**Issue by taestaes** [guochengqian/TENet#17]
The generated .txt file train_pixelshift.txt (9444 Lines) and val_pixelshift.txt (20 Lines) are used for training. check them.

I found that pixelshift training db has 200 files, so running python crop_pixelshift200.py gives 200*28 = 5600 files.
And couldn't understand how can you get 20 val files.

How can I get 9444 files / 20 files for training / val?

**Comment by guochengqian** [comment]
Hi all. For the training/val, we randomly select from all the 1K-cropped images. 

Here is the link to the original dataset: https://drive.google.com/drive/folders/1S1mt9D8IlpSAVm7RTjLheh1hTaltsV_f?usp=share_link

Feel free to have your own split.
