### ISSUE TITLE
Can you release the RGB data of Pixelshift200 datasets?

### ISSUE THREAD

**Issue by zhaowei11594** [guochengqian/TENet#6]
Hi, I use your code in  Prepro.py to product the RGB gt data, but it look like not the full color image? may u provide the full color  RGB picture?

**Comment by guochengqian** [comment]
PixelShift200 data has four channels RGGB. If you need RGB data, the easiest way is to just average the two Green channels.

**Comment by jiangqb** [comment]
Simply average the two green chanels result in blurness. Actually, I got the blur RGB data, we'll appreciate it if you can provide the full color images.

**Comment by guochengqian** [comment]
> Simply average the two green chanels result in blurness. Actually, I got the blur RGB data, we'll appreciate it if you can provide the full color images.

We already release the full-color images. They are in .mat format and have 4 channels. Please check.

**Comment by hyperparameters** [comment]
@jiangqb did find any good way to convert RGGB to RGB?

**Comment by guochengqian** [comment]
Dear all, we will release the original RAW images (4 images / object). These will be done between March 15 th and March 30.

**Comment by ali-space-zzy** [comment]
> Dear all, we will release the original RAW images (4 images / object). These will be done between March 15 th and March 30.

i can not find pixelshift200 dataset in this git , can you release it  --- 2023-2-28
