### ISSUE TITLE
tenet2-dn-ps200.path 

### ISSUE THREAD

**Issue by Shanlans** [guochengqian/TENet#7]
Hi,
May you release your pixelshift 200 pretrained model?

Thanks

**Comment by guochengqian** [comment]
sorry for late reply. I will release it ASAP.

**Comment by Giorat** [comment]
Any news on the release of this model?

**Comment by guochengqian** [comment]
Hello, I'm not the leader of this project anymore. My collaborator want to resubmit our work. I don't think we will release the tenet2-dn-ps200.path.  Sorry for the inconvenience.  However, training the model is very easy. We didn't do any tricky experiment, just train 200 epoches then use the best_model.

**Comment by guochengqian** [comment]
I will close the issue. Feel free to contact me if you need help in training the model.
