### ISSUE TITLE
test using provided model

### ISSUE THREAD

**Issue by wurongyuan** [guochengqian/TENet#9]
Hello,
I take a mosaic image by running rgb2raw.py as imput to test the algorithm,
however, I get a big mosaic image.
rgb:
![image](https://user-images.githubusercontent.com/37181471/72216955-de3f9f00-3562-11ea-9577-54585cc06f57.png)
bayer raw image(input):
![image](https://user-images.githubusercontent.com/37181471/72216960-f0b9d880-3562-11ea-9d6f-e18ac2b9b7d1.png)
big mosaik image(output):
![image](https://user-images.githubusercontent.com/37181471/72216868-c1569c00-3561-11ea-9f5f-196f4f158877.png)
It seems wrong, and I don't the reason, can you help me?

**Comment by wurongyuan** [comment]
the model I have used tenet2-dn-df2k.path

**Comment by wurongyuan** [comment]
I use the tenet2-dn-df2k.path as test model

**Comment by guochengqian** [comment]
i do not where is your issue? The image is too big, so the previous code will crop the image, that is why you saw the boundary.

**Comment by LeeyqSenSe** [comment]
Hi @wurongyuan , where did you get the pretrained model, I can't find it in the readme.
Could you please tell me that, thanks a lot.

**Comment by guochengqian** [comment]
hi everyone,  I will update the code, pretrained model, as well as dataset to the latest version soon (in this month)
